feat: extend doc-build to be windows compatible
ansys/actions pull request #429
Opened 2024-03-19 07:47 UTC by SMoraisAnsys

WIP to extend doc-build action to work with windows and linux.

2024-03-19 07:53 UTC, SMoraisAnsys commented
@RobPasMue Here is a first draft of the modification to allow windows doc build. I need to test it on some repos to ensure that it works correctly but I was able to reach the build command on my fork.

2024-03-19 08:22 UTC, RobPasMue commented
Let me try using PyAnsys Geometry with this one =)

2024-03-19 08:35 UTC, SMoraisAnsys commented
I'll also try to build pyedb with it using linux and windows.

2024-03-19 09:13 UTC, RobPasMue commented
Trying in https://github.com/ansys/pyansys-geometry/pull/1068

2024-03-22 08:02 UTC, jorgepiloto requested changes

2024-03-22 08:02 UTC, jorgepiloto commented on _doc-build-linux/action.yml
> +    description: >
```suggestion
    description: |
```

2024-03-22 08:02 UTC, jorgepiloto commented on doc-build/action.yml
Could we install Python outside the private actions? This is a common step in both and a cross-platform command.

2024-04-10 14:00 UTC, closed without merging