feat: adding ``attrs`` to ignored packages
ansys/actions pull request #658
Opened 2024-12-16 09:45 UTC by germa89

For some reason, ``attrs`` license is not detected, however, it is MIT license:

https://github.com/python-attrs/attrs

This was highlighted here: 

https://github.com/ansys/pymapdl/actions/runs/12349513107/job/34460488022?pr=3569#step:2:5561

2024-12-16 10:14 UTC, RobPasMue commented
That's because somebody complained and they did it recently: see https://github.com/python-attrs/attrs/pull/1377

Somebody.. ehem ehem @SMoraisAnsys - see https://github.com/python-attrs/attrs/issues/1386

Thanks a lot @SMoraisAnsys - I would recommend you pull the latest version @germa89. It should contain the fix and make this PR not necessary anymore

2024-12-16 14:35 UTC, SMoraisAnsys requested changes
I would recommend waiting for changes in `attrs`.

Depending on the changes performed we could still make things work on our sides thanks to the option `--from=mixed` of `pip-licenses` which leverages both Trove classifier (which we could exploit) and package metadata (which we can no longer retrieve). From what I understand of the exchanges I've read it's something related to  the new metadata fields added in metadata version 2.4 (which is used by hatch).

![image](https://github.com/user-attachments/assets/74701b65-94d7-4f60-8a2c-28f30975574a)

2024-12-17 10:06 UTC, germa89 commented
> I would recommend waiting for changes in `attrs`.
> 
> Depending on the changes performed we could still make things work on our sides thanks to the option `--from=mixed` of `pip-licenses` which leverages both Trove classifier (which we could exploit) and package metadata (which we can no longer retrieve). From what I understand of the exchanges I've read it's something related to the new metadata fields added in metadata version 2.4 (which is used by hatch).
> 
> ![image](https://private-user-images.githubusercontent.com/146729917/396133597-74701b65-94d7-4f60-8a2c-28f30975574a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzAwOTksIm5iZiI6MTczNDQyOTc5OSwicGF0aCI6Ii8xNDY3Mjk5MTcvMzk2MTMzNTk3LTc0NzAxYjY1LTk0ZDctNGY2MC04YTJjLTI4ZjMwOTc1NTc0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxMDAzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDRmNzgwOWM1ZTdkNGQ4NTMyODUzYzU3MTUzOWRmNDIxMGYxNmQ0MWE1YTkxOWRkZWFlNjQ1MTlkNWQ1NjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QgUJGTNtG55fGyC4h2bICVOi-dtUuX5lryBSpgF3Phk)

I'm not very fond of waiting many days... I cannot have many PR waiting for a dependency license check. If there is no progress by lunch time, I will do something on PyMAPDL as a temporal fix while they fix this.

2024-12-17 11:43 UTC, RobPasMue commented
> I'm not very fond of waiting many days... I cannot have many PR waiting for a dependency license check. If there is no progress by lunch time, I will do something on PyMAPDL as a temporal fix while they fix this.

You0ve got several options:

* Whitelist it temporarily: https://github.com/ansys/ansys-tools-visualization-interface/pull/215/commits/6836f0364286338ec04571c2aa008e4ad60e6bb7
* Whitelist it from the deps: https://github.com/ansys/pyansys-geometry/pull/1589/files

2024-12-17 11:44 UTC, RobPasMue commented
Just remember to revert it once it's fixed ;)

2024-12-17 11:58 UTC, germa89 commented
> Just remember to revert it once it's fixed ;)

I will!! Thank you! :)

2024-12-19 13:59 UTC, SMoraisAnsys commented
Things seem to be moving "quite fast" and we shouldn't have to wait too much (see https://github.com/python-attrs/attrs/issues/1386#issuecomment-2554081814)

2025-02-11 14:13 UTC, germa89 commented
Closing this PR because we have pushed for individual actions on each repository to mitigate this issue while upstream 'attr' fixes it

2025-02-11 14:13 UTC, closed without merging